title: 'Style Guide NYU Libraries'
baseurl: '/library.nyu.edu-style_guide'
prose:
  siteurl: https://nyulibraries.github.io/library.nyu.edu-style_guide/
  media: images
  rooturl: _guides
  metadata:
    _guides:
      - name: links
        label: Links
        element: textarea
      - name: layout
        label: Layout
        field:
          value: guide
          element: select
          options:
            - name: Guide (preview + code example)
              value: guide
            - name: Article (raw content)
              value: article
          help: "Choose guide (preview + code example) or article (raw content) layouts."
      - name: title
        field:
          element: text
          label: title
      - name: breadcrumbs
        field:
          element: hidden
          value: true
collections:
  guides:
    title: Guides
    output: true
    permalink: "/:collection/:path/"
